import {
  AlignmentType,
  Document,
  Footer,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";

export interface DocxExportOptions {
  filename: string;
  title: string;
  content: string;
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
}

export async function exportToDocx(options: DocxExportOptions) {
  const paragraphs = options.content
    .split(/\n+/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => new Paragraph({ children: [new TextRun({ text: line })] }));

  const documentFile = new Document({
    creator: "Lumae AI",
    title: options.title,
    description: "Content exported from Lumae AI",
    sections: [
      {
        properties: {},
        headers: {},
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: "Lumae AI · lumae.co.in",
                    color: "777780",
                    size: 16,
                  }),
                ],
              }),
            ],
          }),
        },
        children: [
          new Paragraph({
            heading: HeadingLevel.TITLE,
            children: [new TextRun({ text: options.title, bold: true })],
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated by Lumae AI · ${new Date().toLocaleString()}`,
                color: "777780",
                size: 18,
              }),
            ],
          }),
          ...paragraphs,
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(documentFile);
  downloadBlob(blob, options.filename.endsWith(".docx") ? options.filename : `${options.filename}.docx`);
  return true;
}
