import { int, json, mysqlEnum, mysqlTable, text, timestamp, varchar, boolean } from "drizzle-orm/mysql-core";
import { relations } from "drizzle-orm";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  // Subscription tier: 'free' or 'pro'
  subscriptionTier: mysqlEnum("subscriptionTier", ["free", "pro"]).default("free").notNull(),
  // Token balance for free tier users
  tokenBalance: int("tokenBalance").default(100).notNull(),
  // Stripe customer ID for Pro users
  stripeCustomerId: varchar("stripeCustomerId", { length: 255 }),
  // Stripe subscription ID for Pro users
  stripeSubscriptionId: varchar("stripeSubscriptionId", { length: 255 }),
  // Theme preference: 'light', 'dark', 'auto'
  theme: mysqlEnum("theme", ["light", "dark", "auto"]).default("auto").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Content generation history table.
 * Stores all content packages generated by users for session-based retrieval.
 */
export const contentHistory = mysqlTable("contentHistory", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  niche: varchar("niche", { length: 255 }).notNull(),
  targetAudience: varchar("targetAudience", { length: 255 }).notNull(),
  platform: varchar("platform", { length: 100 }).notNull(),
  goal: varchar("goal", { length: 100 }).notNull(),
  contentStyle: varchar("contentStyle", { length: 100 }).notNull(),
  generatedContent: json("generatedContent").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ContentHistory = typeof contentHistory.$inferSelect;
export type InsertContentHistory = typeof contentHistory.$inferInsert;

// Relations
export const usersRelations = relations(users, ({ many }) => ({
  contentHistory: many(contentHistory),
}));

export const contentHistoryRelations = relations(contentHistory, ({ one }) => ({
  user: one(users, {
    fields: [contentHistory.userId],
    references: [users.id],
  }),
}));

/**
 * Token usage tracking table.
 * Tracks daily token consumption for free tier users.
 */
export const tokenUsage = mysqlTable("tokenUsage", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  tokensUsed: int("tokensUsed").notNull(),
  date: timestamp("date").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type TokenUsage = typeof tokenUsage.$inferSelect;
export type InsertTokenUsage = typeof tokenUsage.$inferInsert;

/**
 * Automation schedules table for Pro users.
 * Stores scheduled content generation tasks.
 */
export const automationSchedules = mysqlTable("automationSchedules", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  name: varchar("name", { length: 255 }).notNull(),
  niche: varchar("niche", { length: 255 }).notNull(),
  targetAudience: varchar("targetAudience", { length: 255 }).notNull(),
  platform: varchar("platform", { length: 100 }).notNull(),
  goal: varchar("goal", { length: 100 }).notNull(),
  contentStyle: varchar("contentStyle", { length: 100 }).notNull(),
  // Cron expression for scheduling
  cronExpression: varchar("cronExpression", { length: 100 }).notNull(),
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type AutomationSchedule = typeof automationSchedules.$inferSelect;
export type InsertAutomationSchedule = typeof automationSchedules.$inferInsert;

// Add relations for new tables
export const tokenUsageRelations = relations(tokenUsage, ({ one }) => ({
  user: one(users, {
    fields: [tokenUsage.userId],
    references: [users.id],
  }),
}));

export const automationSchedulesRelations = relations(automationSchedules, ({ one }) => ({
  user: one(users, {
    fields: [automationSchedules.userId],
    references: [users.id],
  }),
}));

// Update users relations to include new tables
export const usersRelationsUpdated = relations(users, ({ many }) => ({
  contentHistory: many(contentHistory),
  tokenUsage: many(tokenUsage),
  automationSchedules: many(automationSchedules),
}));
/**
 * Automation execution logs table.
 * Tracks when automations run and their results.
 */
export const automationExecutionLogs = mysqlTable("automationExecutionLogs", {
  id: int("id").autoincrement().primaryKey(),
  scheduleId: int("scheduleId").notNull(),
  userId: int("userId").notNull(),
  status: mysqlEnum("status", ["success", "failed", "pending"]).default("pending").notNull(),
  generatedContent: json("generatedContent"),
  errorMessage: text("errorMessage"),
  executedAt: timestamp("executedAt").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type AutomationExecutionLog = typeof automationExecutionLogs.$inferSelect;
export type InsertAutomationExecutionLog = typeof automationExecutionLogs.$inferInsert;

/**
 * Content performance analytics table.
 * Tracks engagement metrics for generated content.
 */
export const contentAnalytics = mysqlTable("contentAnalytics", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  contentHistoryId: int("contentHistoryId"),
  platform: varchar("platform", { length: 100 }).notNull(),
  engagement: int("engagement").default(0).notNull(),
  reach: int("reach").default(0).notNull(),
  conversions: int("conversions").default(0).notNull(),
  clicks: int("clicks").default(0).notNull(),
  shares: int("shares").default(0).notNull(),
  comments: int("comments").default(0).notNull(),
  date: timestamp("date").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type ContentAnalytics = typeof contentAnalytics.$inferSelect;
export type InsertContentAnalytics = typeof contentAnalytics.$inferInsert;

// Relations for new tables
export const automationExecutionLogsRelations = relations(automationExecutionLogs, ({ one }) => ({
  user: one(users, {
    fields: [automationExecutionLogs.userId],
    references: [users.id],
  }),
  schedule: one(automationSchedules, {
    fields: [automationExecutionLogs.scheduleId],
    references: [automationSchedules.id],
  }),
}));

export const contentAnalyticsRelations = relations(contentAnalytics, ({ one }) => ({
  user: one(users, {
    fields: [contentAnalytics.userId],
    references: [users.id],
  }),
  contentHistory: one(contentHistory, {
    fields: [contentAnalytics.contentHistoryId],
    references: [contentHistory.id],
  }),
}));


/**
 * Password reset tokens table.
 * Stores temporary tokens for password reset functionality.
 */
export const passwordResetTokens = mysqlTable("passwordResetTokens", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  token: varchar("token", { length: 255 }).notNull().unique(),
  expiresAt: timestamp("expiresAt").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type PasswordResetToken = typeof passwordResetTokens.$inferSelect;
export type InsertPasswordResetToken = typeof passwordResetTokens.$inferInsert;

/**
 * User credits table.
 * Tracks credit balance and transactions for Pro users.
 */
export const userCredits = mysqlTable("userCredits", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull().unique(),
  balance: int("balance").default(0).notNull(),
  totalPurchased: int("totalPurchased").default(0).notNull(),
  totalUsed: int("totalUsed").default(0).notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type UserCredit = typeof userCredits.$inferSelect;
export type InsertUserCredit = typeof userCredits.$inferInsert;

/**
 * Credit transactions table.
 * Logs all credit purchases and usage.
 */
export const creditTransactions = mysqlTable("creditTransactions", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  type: mysqlEnum("type", ["purchase", "usage", "refund"]).notNull(),
  amount: int("amount").notNull(),
  description: text("description"),
  stripePaymentIntentId: varchar("stripePaymentIntentId", { length: 255 }),
  relatedContentId: int("relatedContentId"), // For usage transactions, link to content generation
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type CreditTransaction = typeof creditTransactions.$inferSelect;
export type InsertCreditTransaction = typeof creditTransactions.$inferInsert;

/**
 * Credit packages table.
 * Defines available credit purchase options.
 */
export const creditPackages = mysqlTable("creditPackages", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 100 }).notNull(),
  credits: int("credits").notNull(),
  priceInCents: int("priceInCents").notNull(), // Price in cents for Stripe
  stripePriceId: varchar("stripePriceId", { length: 255 }).notNull().unique(),
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type CreditPackage = typeof creditPackages.$inferSelect;
export type InsertCreditPackage = typeof creditPackages.$inferInsert;

// Relations for credit system tables
export const passwordResetTokensRelations = relations(passwordResetTokens, ({ one }) => ({
  user: one(users, {
    fields: [passwordResetTokens.userId],
    references: [users.id],
  }),
}));

export const userCreditsRelations = relations(userCredits, ({ one }) => ({
  user: one(users, {
    fields: [userCredits.userId],
    references: [users.id],
  }),
}));

export const creditTransactionsRelations = relations(creditTransactions, ({ one }) => ({
  user: one(users, {
    fields: [creditTransactions.userId],
    references: [users.id],
  }),
  content: one(contentHistory, {
    fields: [creditTransactions.relatedContentId],
    references: [contentHistory.id],
  }),
}));

export const creditPackagesRelations = relations(creditPackages, ({ many }) => ({
  transactions: many(creditTransactions),
}));
