import { useMemo, useState } from "react";
import { AlertCircle, CheckCircle2, Clipboard, Loader2, MessageCircle, Plus, Search, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { toast } from "sonner";
import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";

const platformOptions = ["all", "instagram", "facebook", "twitter", "linkedin", "youtube", "tiktok"];

export default function AutoReplyAdvanced() {
  const [tab, setTab] = useState("inbox");
  const [search, setSearch] = useState("");
  const [platform, setPlatform] = useState("all");
  const [drafts, setDrafts] = useState<Record<number, string>>({});
  const [newRule, setNewRule] = useState({ platform: "all", intent: "question", replyTemplate: "" });
  const utils = trpc.useUtils();
  const eventsQuery = trpc.enterprise.getEngagementEvents.useQuery({ limit: 100 });
  const rulesQuery = trpc.enterprise.getAutoReplyRules.useQuery();
  const generate = trpc.enterprise.generateAutoReply.useMutation();
  const updateEvent = trpc.enterprise.updateEngagementEvent.useMutation({ onSuccess: () => utils.enterprise.getEngagementEvents.invalidate() });
  const createRule = trpc.enterprise.createAutoReplyRule.useMutation({ onSuccess: () => utils.enterprise.getAutoReplyRules.invalidate() });
  const events = eventsQuery.data ?? [];
  const rules = rulesQuery.data ?? [];
  const filtered = useMemo(() => events.filter((event) => (platform === "all" || event.platform === platform) && (`${event.authorName} ${event.content}`).toLowerCase().includes(search.toLowerCase())), [events, platform, search]);
  const stats = useMemo(() => ({ total: events.length, awaitingReview: events.filter((event) => !event.autoReplySent && !event.isEscalated).length, autoReplies: events.filter((event) => event.autoReplySent).length, escalated: events.filter((event) => event.isEscalated).length }), [events]);
  const generateDraft = async (event: (typeof events)[number]) => { try { const result = await generate.mutateAsync({ commentContent: event.content, intent: event.intent, platform: event.platform }); setDrafts((current) => ({ ...current, [event.id]: String(result.reply ?? "") })); } catch { toast.error("Could not generate a reply draft."); } };
  const escalate = async (eventId: number) => { try { await updateEvent.mutateAsync({ eventId, isEscalated: true }); toast.success("Event marked for human review."); } catch { toast.error("Could not update this event."); } };
  const addRule = async () => { if (!newRule.replyTemplate.trim()) return toast.error("Enter a reply template first."); try { await createRule.mutateAsync({ platform: newRule.platform === "all" ? undefined : newRule.platform, intent: newRule.intent as "question" | "praise" | "support_issue" | "spam" | "other", replyTemplate: newRule.replyTemplate.trim() }); setNewRule({ platform: "all", intent: "question", replyTemplate: "" }); toast.success("Rule saved."); } catch { toast.error("Could not save the rule."); } };
  return <DashboardLayout><main className="mx-auto w-full max-w-7xl space-y-6 px-4 py-5 sm:px-6"><header><h1 className="text-3xl font-semibold tracking-tight text-foreground">Reply Inbox</h1><p className="mt-2 text-sm text-muted-foreground">Review authentic provider events and create internal reply drafts. Lumae does not claim a reply was sent unless the provider confirms it.</p></header>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Incoming events", stats.total], ["Awaiting review", stats.awaitingReview], ["Provider-confirmed replies", stats.autoReplies], ["Escalated", stats.escalated]].map(([label, value]) => <Card key={label as string}><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold text-foreground">{value as number}</p></CardContent></Card>)}</div>
    <Tabs value={tab} onValueChange={setTab} className="space-y-4"><TabsList className="grid h-auto w-full grid-cols-3 gap-1 bg-muted p-1"><TabsTrigger value="inbox"><MessageCircle className="mr-2 h-4 w-4" />Inbox</TabsTrigger><TabsTrigger value="rules"><Sparkles className="mr-2 h-4 w-4" />Rules</TabsTrigger><TabsTrigger value="analytics"><TrendingUp className="mr-2 h-4 w-4" />Status</TabsTrigger></TabsList>
      <TabsContent value="inbox" className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} className="pl-9" placeholder="Search your incoming events" /></label><Select value={platform} onValueChange={setPlatform}><SelectTrigger className="sm:w-44"><SelectValue /></SelectTrigger><SelectContent>{platformOptions.map((item) => <SelectItem key={item} value={item}>{item === "all" ? "All platforms" : item}</SelectItem>)}</SelectContent></Select></div>{eventsQuery.isLoading ? <Card><CardContent className="p-10 text-center text-muted-foreground"><Loader2 className="mx-auto h-5 w-5 animate-spin" /> <p className="mt-3">Loading events…</p></CardContent></Card> : filtered.length === 0 ? <Card><CardContent className="p-10 text-center"><MessageCircle className="mx-auto h-10 w-10 text-muted-foreground" /><p className="mt-3 font-medium text-foreground">No matching provider events</p><p className="mt-1 text-sm text-muted-foreground">The inbox will remain empty until a connected provider supplies a real message or comment.</p></CardContent></Card> : filtered.map((event) => <Card key={event.id}><CardContent className="space-y-4 p-4"><div className="flex flex-wrap items-center gap-2"><span className="font-medium text-foreground">{event.authorName}</span><Badge variant="outline" className="capitalize">{event.platform}</Badge><Badge variant="secondary" className="capitalize">{event.sentiment}</Badge>{event.isEscalated && <Badge variant="destructive">Human review</Badge>}</div><p className="text-sm text-foreground">{event.content}</p><p className="text-xs text-muted-foreground">Received {new Date(event.createdAt).toLocaleString()}</p>{drafts[event.id] && <div className="rounded-md border border-primary/30 bg-primary/5 p-3"><p className="text-xs font-medium text-primary">Reply draft</p><p className="mt-2 text-sm text-foreground">{drafts[event.id]}</p><Button size="sm" variant="outline" className="mt-3" onClick={() => navigator.clipboard.writeText(drafts[event.id]).then(() => toast.success("Draft copied."))}><Clipboard className="mr-1.5 h-4 w-4" />Copy draft</Button></div>}<div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => generateDraft(event)} disabled={generate.isPending} className="lumae-gradient-cta">{generate.isPending ? <Loader2 className="mr-1.5 h-4 w-4 animate-spin" /> : <Sparkles className="mr-1.5 h-4 w-4" />}Draft reply</Button>{!event.isEscalated && <Button size="sm" variant="outline" onClick={() => escalate(event.id)} disabled={updateEvent.isPending}><AlertCircle className="mr-1.5 h-4 w-4" />Escalate</Button>}</div></CardContent></Card>)}</TabsContent>
      <TabsContent value="rules"><Card><CardHeader><CardTitle>Saved reply rules</CardTitle><CardDescription>Rules are stored for your account. Provider delivery remains subject to connection validation and provider capability.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><Select value={newRule.platform} onValueChange={(value) => setNewRule((current) => ({ ...current, platform: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{platformOptions.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><Select value={newRule.intent} onValueChange={(value) => setNewRule((current) => ({ ...current, intent: value }))}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["question", "praise", "support_issue", "spam", "other"].map((item) => <SelectItem key={item} value={item}>{item.replace("_", " ")}</SelectItem>)}</SelectContent></Select><Button onClick={addRule} disabled={createRule.isPending} className="lumae-gradient-cta"><Plus className="mr-2 h-4 w-4" />Save rule</Button></div><Textarea value={newRule.replyTemplate} onChange={(event) => setNewRule((current) => ({ ...current, replyTemplate: event.target.value }))} placeholder="Reply template for this rule" />{rulesQuery.isLoading ? <p className="text-sm text-muted-foreground">Loading saved rules…</p> : rules.length === 0 ? <p className="rounded-md border border-dashed border-border p-6 text-center text-sm text-muted-foreground">No saved rules.</p> : rules.map((rule) => <div key={rule.id} className="rounded-md border border-border p-3"><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{rule.platform || "All platforms"}</Badge><Badge variant="secondary">{rule.intent.replace("_", " ")}</Badge><Badge variant={rule.isActive ? "default" : "outline"}>{rule.isActive ? "Active" : "Inactive"}</Badge></div><p className="mt-2 text-sm text-foreground">{rule.replyTemplate}</p></div>)}</CardContent></Card></TabsContent>
      <TabsContent value="analytics"><Card><CardContent className="p-8 text-center"><ShieldCheck className="mx-auto h-9 w-9 text-primary" /><p className="mt-3 font-medium text-foreground">No estimated reply analytics</p><p className="mt-1 text-sm text-muted-foreground">Lumae will show measured provider-delivery data only after supported replies are actually delivered and reported by the provider.</p></CardContent></Card></TabsContent>
    </Tabs></main></DashboardLayout>;
}
