import fs from "fs";
import path from "path";
import type { NextFunction, Request, Response } from "express";
type Post={title:string;slug:string;category:string;date:string;excerpt:string;content:string};
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]??c));
const parse=(s:string):Post|null=>{const m=s.match(/^---\s*\n([\s\S]*?)\n---\s*\n([\s\S]*)$/);if(!m)return null;const meta:Record<string,string>={};for(const line of m[1].split("\n")){const i=line.indexOf(":");if(i>=0)meta[line.slice(0,i).trim()]=line.slice(i+1).trim().replace(/^"|"$/g,"");}return{title:meta.title||meta.slug||"Lumae AI Journal",slug:meta.slug||"",category:meta.category||"company",date:meta.date||"",excerpt:meta.excerpt||"",content:m[2].trim()};};
const posts=()=>{const d=path.join(process.cwd(),"client/src/content/blog");if(!fs.existsSync(d))return[] as Post[];return fs.readdirSync(d).filter(f=>f.endsWith(".md")).map(f=>parse(fs.readFileSync(path.join(d,f),"utf8"))).filter((p):p is Post=>Boolean(p)).sort((a,b)=>b.date.localeCompare(a.date));};
const label=(s:string)=>s.split("-").map(w=>w[0].toUpperCase()+w.slice(1)).join(" ");
const shell=()=>{const files=[path.join(process.cwd(),"dist/public/index.html"),path.join(process.cwd(),"client/index.html")];const f=files.find(x=>fs.existsSync(x));return f?fs.readFileSync(f,"utf8"):"";};
const md=(s:string)=>s.split(/\n{2,}/).map(b=>{const t=b.trim();if(!t)return"";if(t.startsWith("### "))return`<h3>${esc(t.slice(4))}</h3>`;if(t.startsWith("## "))return`<h2>${esc(t.slice(3))}</h2>`;if(t.startsWith("# "))return`<h2>${esc(t.slice(2))}</h2>`;return`<p>${esc(t).replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>")}</p>`;}).join("");
const render=(base:string,title:string,h1:string,canonicalPath:string,body:string,links:{href:string;text:string}[])=>{const nav=links.map(l=>`<a href="${l.href}">${esc(l.text)}</a>`).join(" | ");const seo=`<div id="seo-content" style="position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap"><nav>${nav}</nav><main><h1>${esc(h1)}</h1>${body}</main></div>`;let out=base.replace(/<title>[^<]*<\/title>/i,`<title>${esc(title)}</title>`).replace(/<link rel="canonical"[^>]*>/i,"");out=out.replace("</head>",`<link rel="canonical" href="https://lumae.co.in${canonicalPath}" />\n</head>`);return out.replace("<body>",`<body>\n${seo}`);};
export function seoMiddleware(req:Request,res:Response,next:NextFunction){if(req.method!=="GET"||!req.accepts("html"))return next();const base=shell();if(!base)return next();const all=posts(),p=req.path,common=[{href:"/",text:"Home"},{href:"/blog",text:"Journal"},{href:"/pricing",text:"Plans"}];if(p==="/")return res.type("html").send(render(base,"Lumae AI - AI-Powered Social Media Automation","Lumae AI - AI-Powered Social Media Automation","/","<p>Lumae AI helps creators and businesses generate, schedule, and automate social media content without losing their voice.</p><p>Create posts and scripts, repurpose content, plan campaigns, and manage connected social channels from one workspace.</p>",[...common,{href:"/login",text:"Start creating"}]));if(p==="/blog"){const body=all.map(x=>`<article><h2><a href="/blog/${x.category}/${x.slug}">${esc(x.title)}</a></h2><p>${esc(x.excerpt)}</p></article>`).join("");return res.type("html").send(render(base,"Journal - Lumae AI","Lumae AI Journal","/blog",body,[...common,{href:"/blog/category/company",text:"Company"},{href:"/blog/category/marketing-tips",text:"Marketing Tips"},{href:"/blog/category/product-updates",text:"Product Updates"}]));}if(p.startsWith("/blog/category/")){const c=p.slice(15),items=all.filter(x=>x.category===c);if(!items.length)return next();const body=items.map(x=>`<article><h2><a href="/blog/${x.category}/${x.slug}">${esc(x.title)}</a></h2><p>${esc(x.excerpt)}</p></article>`).join("");return res.type("html").send(render(base,`${label(c)} - Lumae AI Journal`,`${label(c)} Articles`,p,body,[...common,{href:"/blog",text:"All posts"}]));}const m=p.match(/^\/blog\/([^/]+)\/([^/]+)$/);if(m){const x=all.find(q=>q.category===m[1]&&q.slug===m[2]);if(!x)return next();const related=all.filter(q=>q.slug!==x.slug).slice(0,3).map(q=>`<p><a href="/blog/${q.category}/${q.slug}">${esc(q.title)}</a></p>`).join("");return res.type("html").send(render(base,`${x.title} - Lumae AI`,x.title,p,`<p>${esc(x.excerpt)}</p>${md(x.content)}<aside><h2>Related reading</h2>${related}</aside>`,[...common,{href:`/blog/category/${x.category}`,text:label(x.category)}]));}return next();}
